import React from 'react';
import { Helmet } from 'react-helmet';
import {
  Box,
  Container,
  Heading,
  Text,
  VStack,
  List,
  ListItem,
} from '@chakra-ui/react';

const BrewlePrivacy = () => {
  return (
    <>
      <Helmet>
        <title>Brewle - Privacy Policy</title>
        <meta
          name="description"
          content="Privacy Policy for Brewle mobile application."
        />
        <meta name="robots" content="noindex, nofollow" />
        <link
          rel="canonical"
          href="https://nurullahgundogdu.com/brewle-privacy"
        />
      </Helmet>
      <Box
        as="main"
        minH="calc(100vh - 70px)"
        py={{ base: 10, md: 20 }}
        position="relative"
      >
        <Container maxW="container.md">
          <VStack align="stretch" spacing={6}>
            <Heading
              as="h1"
              size={{ base: 'xl', md: '2xl' }}
              bgGradient="linear(to-r, retro.neonPink, retro.neonPurple)"
              bgClip="text"
            >
              Privacy Policy for Brewle
            </Heading>

            <Text color="gray.300" fontSize="sm">
              Last Updated: January 27, 2026
            </Text>

            <Text color="gray.300">
              Brewle (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is
              committed to protecting your privacy. This Privacy Policy
              explains how your information is collected, used, and disclosed by
              Brewle.
            </Text>

            <Text color="gray.300">
              By accessing or using our mobile application, you signify that you
              have read, understood, and agree to our collection, storage, use,
              and disclosure of your personal information as described in this
              Privacy Policy.
            </Text>

            <Box>
              <Heading as="h2" size="md" mb={2}>
                1. Information We Collect
              </Heading>
              <Text color="gray.300" mb={3}>
                We believe in minimizing data collection. Brewle is designed to
                be used anonymously without creating a traditional user account
                (no email or phone number required).
              </Text>

              <Heading as="h3" size="sm" mb={1}>
                A. Device Information
              </Heading>
              <Text color="gray.300" mb={2}>
                We collect a unique Device ID generated by your device.
              </Text>
              <Text color="gray.300" mb={3}>
                <strong>Purpose:</strong> To distinguish your device from others
                in real-time features (e.g., to prevent multiple active brewing
                sessions from the same device) and to store your local brewing
                history.
              </Text>

              <Heading as="h3" size="sm" mb={1}>
                B. Usage Data
              </Heading>
              <Text color="gray.300" mb={2}>
                We collect anonymous data regarding your interactions with the
                app, such as:
              </Text>
              <List styleType="disc" pl={6} spacing={1} mb={3}>
                <ListItem color="gray.300">
                  Brewing mode selected (Tea vs. Coffee).
                </ListItem>
                <ListItem color="gray.300">
                  Duration of brewing sessions.
                </ListItem>
                <ListItem color="gray.300">
                  Timestamps of when sessions start and end.
                </ListItem>
              </List>

              <Heading as="h3" size="sm" mb={1}>
                C. Communications (Chat Data)
              </Heading>
              <Text color="gray.300" mb={2}>
                When you use the &quot;Chat Room&quot; feature:
              </Text>
              <List styleType="disc" pl={6} spacing={1} mb={3}>
                <ListItem color="gray.300">
                  <strong>Ephemeral Messaging:</strong> Messages you send are
                  stored temporarily on our servers to facilitate real-time
                  communication.
                </ListItem>
                <ListItem color="gray.300">
                  <strong>Automatic Deletion:</strong> Our system is designed to
                  automatically delete messages from our servers shortly after
                  the brewing session expires. We do not maintain a permanent
                  archive of chat logs.
                </ListItem>
                <ListItem color="gray.300">
                  <strong>Content Filtering:</strong> Messages are processed
                  locally and server-side to filter profanity.
                </ListItem>
              </List>

              <Heading as="h3" size="sm" mb={1}>
                D. Technical Data
              </Heading>
              <Text color="gray.300">
                Like most applications, our servers automatically record certain
                information, such as your IP address, strictly for security
                purposes (e.g., to prevent abuse, spam, or DDoS attacks).
              </Text>
            </Box>

            <Box>
              <Heading as="h2" size="md" mb={2}>
                2. How We Use Your Information
              </Heading>
              <Text color="gray.300" mb={2}>
                We use the information we collect for the following purposes:
              </Text>
              <List styleType="disc" pl={6} spacing={1}>
                <ListItem color="gray.300">
                  <strong>To Provide the Service:</strong> To operate the timer,
                  sync real-time status with other users, and facilitate the
                  chat room.
                </ListItem>
                <ListItem color="gray.300">
                  <strong>To Improve the App:</strong> To analyze aggregate
                  statistics (e.g., &quot;Total Coffees Brewed Globaly&quot;)
                  to understand user preferences.
                </ListItem>
                <ListItem color="gray.300">
                  <strong>Security:</strong> To detect and prevent fraudulent or
                  abusive activity.
                </ListItem>
              </List>
            </Box>

            <Box>
              <Heading as="h2" size="md" mb={2}>
                3. Data Retention
              </Heading>
              <List styleType="disc" pl={6} spacing={1}>
                <ListItem color="gray.300">
                  <strong>Active Sessions:</strong> Data related to your current
                  brewing status is stored only while the session is active.
                </ListItem>
                <ListItem color="gray.300">
                  <strong>Chat Messages:</strong> Messages are ephemeral and are
                  automatically deleted from our database after a set period
                  (typically 10–20 minutes after creation).
                </ListItem>
                <ListItem color="gray.300">
                  <strong>Brewing History:</strong> Anonymous statistics (e.g.,
                  total brew count) are linked to your Device ID and stored
                  indefinitely to provide you with your personal statistics,
                  unless you clear your app data.
                </ListItem>
              </List>
            </Box>

            <Box>
              <Heading as="h2" size="md" mb={2}>
                4. Third-Party Services
              </Heading>
              <Text color="gray.300" mb={2}>
                We may use third-party service providers to help us operate our
                application. These third parties may have access to your data
                only to perform tasks on our behalf and are obligated not to
                disclose or use it for any other purpose.
              </Text>
              <List styleType="disc" pl={6} spacing={1}>
                <ListItem color="gray.300">
                  <strong>PocketBase &amp; Railway:</strong> Used for backend
                  hosting and database management.
                </ListItem>
                <ListItem color="gray.300">
                  <strong>Expo:</strong> Used for development and push
                  notification services.
                </ListItem>
                <ListItem color="gray.300">
                  <strong>Google Play Services &amp; Apple App Store:</strong>{' '}
                  Used for app distribution and essential device services.
                </ListItem>
              </List>
            </Box>

            <Box>
              <Heading as="h2" size="md" mb={2}>
                5. Security
              </Heading>
              <Text color="gray.300">
                We take reasonable measures to protect your information from
                unauthorized access, use, or disclosure. However, no internet or
                mobile application transmission is ever fully secure or
                error-free.
              </Text>
            </Box>

            <Box>
              <Heading as="h2" size="md" mb={2}>
                6. Children&apos;s Privacy
              </Heading>
              <Text color="gray.300">
                Brewle does not knowingly collect personal information from
                children under the age of 13. If we discover that a child under
                13 has provided us with personal information, we will delete
                such information from our servers immediately.
              </Text>
            </Box>

            <Box>
              <Heading as="h2" size="md" mb={2}>
                7. Changes to This Privacy Policy
              </Heading>
              <Text color="gray.300">
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page. You are advised to review this Privacy Policy
                periodically for any changes.
              </Text>
            </Box>

            <Box mb={4}>
              <Heading as="h2" size="md" mb={2}>
                8. Contact Us
              </Heading>
              <Text color="gray.300" mb={1}>
                If you have any questions about this Privacy Policy, please
                contact us at:
              </Text>
              <Text color="gray.300">
                Email:{' '}
                <a href="mailto:info@nurullahgundogdu.com">
                  info@nurullahgundogdu.com
                </a>
              </Text>
              <Text color="gray.300">Developer: Nurullah Gundogdu</Text>
            </Box>
          </VStack>
        </Container>
      </Box>
    </>
  );
};

export default BrewlePrivacy;

